//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int id_proveedor { get; set; }
        public string nombre { get; set; }
        public string cuit { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
    }
}
